apiVersion: v1
kind: Service
metadata:
 name: svc-lanzador
spec:
 type: LoadBalancer
# Comentado de la version  local usando minikube
# type: ClusterIP
 selector:
  app: pod-lanzador
 ports:
 - protocol: TCP
   port: 80
   targetPort: 3000
