apiVersion: apps/v1
kind: Deployment
metadata:
 name: depl-secrets
 labels:
  app: pod-secrets
spec:
 replicas: 1
 selector:
  matchLabels:
   app: pod-secrets
 template:
  metadata:
   labels:
    app: pod-secrets
  spec:
   containers:
   - name: cont-secrets
     image: t23-minimal-web-w-lanzador
     imagePullPolicy: Never
     env:
     - name: T23_SECRET_1
       valueFrom:
        secretKeyRef:
         name: sec-app1-secret
         key: first-secret
     - name: T23_SECRET_2
       valueFrom:
        secretKeyRef:
         name: sec-app1-secret
         key: second-secret
     - name: T23_LA_CMD_APP
       value: "node ../../T23-minimal-web/src/server.js > /tmp/server.js.log 2>&1"
     ports:
     - containerPort: 3000
