apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-vault-server-app1
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secret-store-vault-server
    kind: SecretStore
  target:
    name: sec-replicated-app1
  data:
  - secretKey: replicated-first-secret
    remoteRef:
      key: app1
      property: first-secret
  - secretKey: replicated-second-secret
    remoteRef:
      key: app1
      property: second-secret
  - secretKey: replicated-app1-secrets
    remoteRef:
      key: app1
#---
# will create a secret with:
#kind: Secret
#metadata:
#  name: sec-replicated-app1
#data:
#  replicated-first-secret: xxx # Base64 del secreto
#  replicated-second-secret: xxx # Base64 del secreto
#  replicated-app1-secrets: xxx # Base64 del json con el KV map
