apiVersion: v1
kind: Secret
metadata:
  name: sec-vault-token
data:
  password: xxxBASE64_VAULT_PASSxxx # base64 de la contraseña
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store-vault-server
spec:
  provider:
    vault:
      server: "xxxVAULT_ADDRxxx" 
      path: "secret"
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      # Controlado con vault secrets list -detailed
      version: "v2"
      auth:
        # VaultUserPass authenticates with Vault using the UserPass auth mechanism
        # https://www.vaultproject.io/docs/auth/userpass
        userPass:
          # Path where the UserPass authentication backend is mounted
          path: "userpass"
          username: "xxxVAULT_USERxxx"
          secretRef:
            name: "sec-vault-token"
            key: "password"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-vault-server-app1
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secret-store-vault-server
    kind: SecretStore
  target:
    name: sec-replicated-app1
  data:
  - secretKey: replicated-first-secret
    remoteRef:
      key: app1
      property: first-secret
  - secretKey: replicated-second-secret
    remoteRef:
      key: app1
      property: second-secret
  - secretKey: replicated-app1-secrets
    remoteRef:
      key: app1
#---
# will create a secret with:
#kind: Secret
#metadata:
#  name: sec-replicated-app1
#data:
#  replicated-first-secret: xxx # Base64 del secreto
#  replicated-app1-secrets: xxx # Base64 del json con el KV map
